language: go
go:
  - 1.11
env:
  global:
    - COVERALLS_PARALLEL=true
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -v ./...

